# frozen_string_literal: true

require_relative "views/base_view"
require_relative "views/funnel_view"
require_relative "views/conversions_view"
require_relative "views/engagement_view"
require_relative "views/page_report_view"
require_relative "views/analytics_index_view"
require_relative "views/segments_view"
require_relative "views/forms_view"
require_relative "views/heatmap_view"
require_relative "views/export_view"
require_relative "views/import_view"
require_relative "views/analyzer_view"
require_relative "views/scroll_view"
require_relative "views/vitals_view"
require_relative "views/frustration_view"
require_relative "views/sessions_index_view"
require_relative "views/session_show_view"
require_relative "views/event_show_view"
require_relative "views/events_index_view"
require_relative "views/errors_index_view"
require_relative "views/client_error_show_view"
require_relative "views/problem_show_view"
